apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kargo.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    kubernetes.io/ingress.allow-http: "false"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
    networking.gke.io/ssl-redirect: "true" 
    cert-manager.io/cluster-issuer: {{ .Values.cert.issuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.cert.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kargo-api
                port:
                  number: 443
