apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cert.secretName }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.cert.issuer }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cert.tlsCrt | quote }}
  tls.key: {{ .Values.cert.tlsKey | quote }}
